/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.duoc.pty.feriavirtualdesktop.grafica;

import cl.duoc.pty.feriavirtualdesktop.entidades.Orden;
import cl.duoc.pty.feriavirtualdesktop.entidades.Proceso;
import cl.duoc.pty.feriavirtualdesktop.entidades.RespuestaFirmarOrden;
import cl.duoc.pty.feriavirtualdesktop.entidades.RespuestaOrden;
import cl.duoc.pty.feriavirtualdesktop.entidades.RespuestaOrdenListar;
import cl.duoc.pty.feriavirtualdesktop.entidades.RespuestaProceso;
import cl.duoc.pty.feriavirtualdesktop.entidades.RespuestaProcesoListar;
import cl.duoc.pty.feriavirtualdesktop.entidades.TMOrden;
import cl.duoc.pty.feriavirtualdesktop.entidades.TMProceso;
import cl.duoc.pty.feriavirtualdesktop.negocio.OrdenController;
import cl.duoc.pty.feriavirtualdesktop.negocio.ProcesoController;
import cl.duoc.pty.feriavirtualdesktop.utils.ValidarRut;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;

/**
 *
 * @author bruunildo
 */
public class VistaProcesosVenta extends javax.swing.JPanel {

    /**
     * Creates new form VistaProcesosVenta
     */
    
    public VistaProcesosVenta() {
        initComponents();
        inicializarTabla();
        listarOrdenes();
        listarProcesos();
        setearBotones();
        
    }
    
    private void inicializarTabla() {
        List<Orden> ordenes = new ArrayList<>();
        TMOrden modelo;           
        modelo = new TMOrden(ordenes);

        tblOrdenes.setModel(modelo); 

    }
    
    private void setearBotones() {
        
        btnFirmarOrden.setEnabled(false);
        btnCrearProceso.setEnabled(false);
        btnModificarProceso.setEnabled(false);
        btnAnularProceso.setEnabled(false);
        
    }
    
    private void listarOrdenes() {
        RespuestaOrdenListar listaOrden = new RespuestaOrdenListar();
    
        listaOrden = OrdenController.listarOrden();

        TMOrden modelo;
        modelo = new TMOrden(listaOrden.getOrdenes());

        tblOrdenes.setModel(modelo);
    }
    
    private void listarProcesos() {
        RespuestaProcesoListar listaProceso = new RespuestaProcesoListar();
    
        listaProceso = ProcesoController.listarProceso();

        TMProceso modelo;
        modelo = new TMProceso(listaProceso.getProcesos());

        tblProcesos.setModel(modelo);
    }
    
    private void limpiarCampos() {
        txtIdOrden.setText("");
        txtCliente.setText("");
        txtFechaOrden.setText("");
        txtEstadoOrden.setText("");
        txtIdProceso.setText("");
        txtFechaProceso.setText("");
        txtEstadoProceso.setText("");
        txtPagoTransportista.setText("");
        txtComision.setText("");
        txtAduana.setText("");
        txtPagoServicio.setText("");
        txtIdUsuario.setText("");
        txtFechaFinProceso.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlProcesosVenta = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdOrden = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        txtFechaOrden = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdProceso = new javax.swing.JTextField();
        txtEstadoOrden = new javax.swing.JTextField();
        txtComision = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtAduana = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPagoServicio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPagoTransportista = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtFechaProceso = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtEstadoProceso = new javax.swing.JTextField();
        btnBuscarOrden = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtIdUsuario = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtFechaFinProceso = new javax.swing.JTextField();
        btnFirmarOrden = new javax.swing.JButton();
        btnCrearProceso = new javax.swing.JButton();
        btnModificarProceso = new javax.swing.JButton();
        btnAnularProceso = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrdenes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProcesos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        btnActualizarOrdenesProcesos = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1100, 640));

        pnlProcesosVenta.setBackground(new java.awt.Color(255, 255, 255));
        pnlProcesosVenta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Procesos de Venta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ID Orden");

        txtIdOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdOrdenActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Cliente");

        txtCliente.setEditable(false);
        txtCliente.setBackground(new java.awt.Color(204, 204, 204));

        txtFechaOrden.setEditable(false);
        txtFechaOrden.setBackground(new java.awt.Color(204, 204, 204));
        txtFechaOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaOrdenActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Fecha");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Estado");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("ID Proceso");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Valor Aduana");

        txtIdProceso.setEditable(false);
        txtIdProceso.setBackground(new java.awt.Color(204, 204, 204));

        txtEstadoOrden.setEditable(false);
        txtEstadoOrden.setBackground(new java.awt.Color(204, 204, 204));
        txtEstadoOrden.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtEstadoOrdenInputMethodTextChanged(evt);
            }
        });
        txtEstadoOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoOrdenActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Comisión");

        txtAduana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAduanaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Pago por Servicio");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Pago Transportista");

        txtPagoTransportista.setEditable(false);
        txtPagoTransportista.setBackground(new java.awt.Color(204, 204, 204));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Estado Proceso");

        txtFechaProceso.setEditable(false);
        txtFechaProceso.setBackground(new java.awt.Color(204, 204, 204));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Fecha Proceso");

        txtEstadoProceso.setEditable(false);
        txtEstadoProceso.setBackground(new java.awt.Color(204, 204, 204));

        btnBuscarOrden.setBackground(new java.awt.Color(253, 187, 52));
        btnBuscarOrden.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscarOrden.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarOrden.setText("Buscar");
        btnBuscarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarOrdenActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("ID ");

        txtIdUsuario.setEditable(false);
        txtIdUsuario.setBackground(new java.awt.Color(204, 204, 204));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Fecha Fin Proceso");

        txtFechaFinProceso.setEditable(false);
        txtFechaFinProceso.setBackground(new java.awt.Color(204, 204, 204));

        btnFirmarOrden.setBackground(new java.awt.Color(0, 153, 153));
        btnFirmarOrden.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnFirmarOrden.setForeground(new java.awt.Color(255, 255, 255));
        btnFirmarOrden.setText("Firmar Orden");
        btnFirmarOrden.setBorder(null);
        btnFirmarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirmarOrdenActionPerformed(evt);
            }
        });

        btnCrearProceso.setBackground(new java.awt.Color(0, 153, 153));
        btnCrearProceso.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnCrearProceso.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearProceso.setText("Crear Proceso");
        btnCrearProceso.setBorder(null);
        btnCrearProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProcesoActionPerformed(evt);
            }
        });

        btnModificarProceso.setBackground(new java.awt.Color(253, 187, 52));
        btnModificarProceso.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnModificarProceso.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarProceso.setText("Modificar");
        btnModificarProceso.setBorder(null);
        btnModificarProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProcesoActionPerformed(evt);
            }
        });

        btnAnularProceso.setBackground(new java.awt.Color(229, 52, 63));
        btnAnularProceso.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAnularProceso.setForeground(new java.awt.Color(255, 255, 255));
        btnAnularProceso.setText("Anular");
        btnAnularProceso.setBorder(null);
        btnAnularProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularProcesoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnFirmarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)
                        .addComponent(btnCrearProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnularProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel8))
                                    .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(txtFechaOrden, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(txtEstadoOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtIdOrden)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnBuscarOrden)
                                    .addGap(6, 6, 6))))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdProceso, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFechaProceso, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEstadoProceso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addComponent(txtPagoTransportista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPagoServicio)
                            .addComponent(txtAduana)
                            .addComponent(txtComision)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel12)
                                    .addComponent(txtFechaFinProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComision, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarOrden, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdUsuario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(txtAduana))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFechaProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFechaOrden, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(txtEstadoProceso)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPagoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPagoTransportista, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtEstadoOrden, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtFechaFinProceso))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirmarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnularProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tblOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblOrdenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrdenesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrdenes);

        tblProcesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblProcesos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProcesosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProcesos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );

        btnLimpiar.setBackground(new java.awt.Color(253, 187, 52));
        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(null);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnActualizarOrdenesProcesos.setBackground(new java.awt.Color(253, 187, 52));
        btnActualizarOrdenesProcesos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnActualizarOrdenesProcesos.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarOrdenesProcesos.setText("Actualizar");
        btnActualizarOrdenesProcesos.setBorder(null);
        btnActualizarOrdenesProcesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarOrdenesProcesosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProcesosVentaLayout = new javax.swing.GroupLayout(pnlProcesosVenta);
        pnlProcesosVenta.setLayout(pnlProcesosVentaLayout);
        pnlProcesosVentaLayout.setHorizontalGroup(
            pnlProcesosVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProcesosVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProcesosVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlProcesosVentaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(449, 449, 449))))
            .addGroup(pnlProcesosVentaLayout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnActualizarOrdenesProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlProcesosVentaLayout.setVerticalGroup(
            pnlProcesosVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProcesosVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProcesosVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnActualizarOrdenesProcesos, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlProcesosVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlProcesosVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtIdOrden.setEditable(true);
        txtIdOrden.setText("");
        txtCliente.setText("");
        txtFechaOrden.setText("");
        txtEstadoOrden.setText("");
        txtIdProceso.setText("");
        txtFechaProceso.setText("");
        txtEstadoProceso.setText("");
        txtPagoTransportista.setText("");
        txtComision.setText("");
        txtAduana.setText("");
        txtPagoServicio.setText("");
        txtIdUsuario.setText("");
        txtFechaFinProceso.setText("");
        
        setearBotones();
        
                
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnModificarProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProcesoActionPerformed
        if(txtIdOrden.getText().isEmpty() ||
                txtComision.getText().isEmpty() ||
                txtAduana.getText().isEmpty() ||
                txtPagoServicio.getText().isEmpty()) {
            
        showMessageDialog(null, "Hay campos vacíos","Información",JOptionPane.WARNING_MESSAGE);
        
        } 
        
        else {
            
        RespuestaProceso modificarProceso = new RespuestaProceso();
        Proceso proceso = new Proceso();
        
        Date fechaProceso = new Date();
        Date fechaFinProceso = new Date();
        
        String fecha = txtFechaFinProceso.getText();
        try {
            fechaFinProceso = new SimpleDateFormat("EEE MMM dd HH:mm:ss z YYYY", Locale.ENGLISH).parse(txtFechaFinProceso.getText());
            fechaProceso = new SimpleDateFormat("EEE MMM dd HH:mm:ss z YYYY", Locale.ENGLISH).parse(txtFechaProceso.getText());
        } catch (ParseException ex) {
            System.out.println("Error "+ex);
        }
        
        proceso.setIdProceso(Integer.valueOf(txtIdProceso.getText()));
        proceso.setIdUsuario(1);
        proceso.setIdOrden(Integer.valueOf(txtIdOrden.getText()));
        proceso.setComision(Integer.valueOf(txtComision.getText()));
        proceso.setValorAduana(Integer.valueOf(txtAduana.getText()));
        proceso.setPagoPorServicio(Integer.valueOf(txtPagoServicio.getText()));
        proceso.setPagoTransportista(Integer.valueOf(txtPagoTransportista.getText()));
        proceso.setEstadoProceso(txtEstadoProceso.getText());
        proceso.setFechaProceso(fechaProceso);
        //TODO agregar calendario
        proceso.setFechaFinProceso(fechaFinProceso);
        
        modificarProceso = ProcesoController.crearModificarProceso(proceso);
        
        showMessageDialog(null, modificarProceso.getMensaje(),"Información",JOptionPane.WARNING_MESSAGE);
        limpiarCampos();
        btnModificarProceso.setEnabled(false);
        txtIdOrden.setEditable(true);
        }
    }//GEN-LAST:event_btnModificarProcesoActionPerformed

    private void tblOrdenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrdenesMouseClicked
        
        txtIdOrden.setEditable(false);
        int i = tblOrdenes.getSelectedRow();
        TableModel model = tblOrdenes.getModel();
        
        txtIdOrden.setText(model.getValueAt(i,0).toString());
        txtIdUsuario.setText(model.getValueAt(i,2).toString());
        txtFechaOrden.setText(model.getValueAt(i,1).toString());
        txtEstadoOrden.setText(model.getValueAt(i,3).toString());
        
        if("PENDIENTE".equals(txtEstadoOrden.getText())) {
        
            btnFirmarOrden.setEnabled(true);
        }
        else {
            btnFirmarOrden.setEnabled(false);
            btnCrearProceso.setEnabled(true);
        }
    }//GEN-LAST:event_tblOrdenesMouseClicked

    private void txtEstadoOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoOrdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoOrdenActionPerformed

    private void txtFechaOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaOrdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaOrdenActionPerformed

    private void txtIdOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdOrdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdOrdenActionPerformed

    private void txtAduanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAduanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAduanaActionPerformed

    private void btnFirmarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirmarOrdenActionPerformed
        RespuestaFirmarOrden firmaOrden = new RespuestaFirmarOrden();
                
        firmaOrden = OrdenController.firmarOrden(txtIdOrden.getText());
        
        showMessageDialog(null, firmaOrden.getMensaje(),"Información",JOptionPane.WARNING_MESSAGE);
        btnFirmarOrden.setEnabled(false);
        limpiarCampos();
        txtIdOrden.setEditable(true);
    }//GEN-LAST:event_btnFirmarOrdenActionPerformed

    private void tblProcesosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProcesosMouseClicked
        
        setearBotones();
        btnCrearProceso.setEnabled(false);
        txtIdOrden.setEditable(false);
        btnModificarProceso.setEnabled(true);
        
        int i = tblProcesos.getSelectedRow();
        TableModel model = tblProcesos.getModel();
        
        txtIdOrden.setText(model.getValueAt(i,0).toString());
        txtIdProceso.setText(model.getValueAt(i,1).toString());
        txtAduana.setText(model.getValueAt(i,2).toString());
        txtPagoServicio.setText(model.getValueAt(i,3).toString());
        txtPagoTransportista.setText(model.getValueAt(i,4).toString());
        txtFechaProceso.setText(model.getValueAt(i,5).toString());
        txtEstadoProceso.setText(model.getValueAt(i,6).toString());
        txtComision.setText(model.getValueAt(i,7).toString());
        txtFechaFinProceso.setText(model.getValueAt(i,9).toString());
        
        if(!"ANULADO".equals(txtEstadoProceso.getText())) {
            btnAnularProceso.setEnabled(true);
        }
        
    }//GEN-LAST:event_tblProcesosMouseClicked

    private void btnBuscarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarOrdenActionPerformed
        
       RespuestaOrden orden = new RespuestaOrden();
                
       orden = OrdenController.buscarOrden(txtIdOrden.getText()); 
       
       if(orden.isExito()) {
       txtFechaOrden.setText(orden.getOrden().getFechaOrden().toString());
       txtEstadoOrden.setText(orden.getOrden().getEstado());
       txtIdUsuario.setText(String.valueOf(orden.getOrden().getIdClienteExterno()));
       
        if("PENDIENTE".equals(txtEstadoOrden.getText())) {
        
            btnFirmarOrden.setEnabled(true);
        }
        else {
            btnFirmarOrden.setEnabled(false);
            btnCrearProceso.setEnabled(true);
        }   
       }
       else {
           limpiarCampos();
           setearBotones();
           showMessageDialog(null, orden.getMensaje(),"Información",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_btnBuscarOrdenActionPerformed

    private void txtEstadoOrdenInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtEstadoOrdenInputMethodTextChanged
         
    }//GEN-LAST:event_txtEstadoOrdenInputMethodTextChanged

    private void btnCrearProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearProcesoActionPerformed
        if(txtIdOrden.getText().isEmpty() ||
                txtComision.getText().isEmpty() ||
                txtAduana.getText().isEmpty() ||
                txtPagoServicio.getText().isEmpty()) {
            
        showMessageDialog(null, "Hay campos vacíos","Información",JOptionPane.WARNING_MESSAGE);

        } else {
        RespuestaProceso creacionProceso = new RespuestaProceso();
        Proceso proceso = new Proceso();
        
        Date date = new Date();
        
        proceso.setIdProceso(0);
        proceso.setIdUsuario(1);
        proceso.setIdOrden(Integer.valueOf(txtIdOrden.getText()));
        proceso.setComision(Integer.valueOf(txtComision.getText()));
        proceso.setValorAduana(Integer.valueOf(txtAduana.getText()));
        proceso.setPagoPorServicio(Integer.valueOf(txtPagoServicio.getText()));
        proceso.setPagoTransportista(0);
        proceso.setEstadoProceso("PENDIENTE");
        proceso.setFechaProceso(date);
        //TODO agregar calendario
        proceso.setFechaFinProceso(date);
        
        creacionProceso = ProcesoController.crearModificarProceso(proceso);
        
        showMessageDialog(null, creacionProceso.getMensaje(),"Información",JOptionPane.WARNING_MESSAGE);
        limpiarCampos();
        btnCrearProceso.setEnabled(false);
        txtIdOrden.setEditable(true);
        }
    }//GEN-LAST:event_btnCrearProcesoActionPerformed

    private void btnActualizarOrdenesProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarOrdenesProcesosActionPerformed
        listarOrdenes();
        listarProcesos();     
    }//GEN-LAST:event_btnActualizarOrdenesProcesosActionPerformed

    private void btnAnularProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularProcesoActionPerformed
        RespuestaProceso anularProceso = new RespuestaProceso();
        Proceso proceso = new Proceso();
        
        Date fechaProceso = new Date();
        Date fechaFinProceso = new Date();
        //DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEE MMM dd HH:mm:ss z YYYY");
        //ZonedDateTime today = ZonedDateTime.now();
        
        
        try {
            //today = ZonedDateTime.parse(txtFechaFinProceso.getText(), formatter).plusMonths(1);
            fechaFinProceso = new SimpleDateFormat("EEE MMM dd HH:mm:ss z YYYY", Locale.ENGLISH).parse(txtFechaFinProceso.getText());
            fechaProceso = new SimpleDateFormat("EEE MMM dd HH:mm:ss z YYYY", Locale.ENGLISH).parse(txtFechaProceso.getText());
        } catch (ParseException ex) {
            System.out.println("Error "+ex);
        }
        
        proceso.setIdProceso(Integer.valueOf(txtIdProceso.getText()));
        proceso.setIdUsuario(1);
        proceso.setIdOrden(Integer.valueOf(txtIdOrden.getText()));
        proceso.setComision(Integer.valueOf(txtComision.getText()));
        proceso.setValorAduana(Integer.valueOf(txtAduana.getText()));
        proceso.setPagoPorServicio(Integer.valueOf(txtPagoServicio.getText()));
        proceso.setPagoTransportista(Integer.valueOf(txtPagoTransportista.getText()));
        proceso.setEstadoProceso("ANULADO");
        proceso.setFechaProceso(fechaProceso);
        //TODO agregar calendario
        proceso.setFechaFinProceso(fechaFinProceso);
        
        anularProceso = ProcesoController.crearModificarProceso(proceso);
        
        showMessageDialog(null, anularProceso.getMensaje(),"Información",JOptionPane.WARNING_MESSAGE);
        limpiarCampos();
        btnAnularProceso.setEnabled(false);
        btnModificarProceso.setEnabled(false);
        txtIdOrden.setEditable(true);

    }//GEN-LAST:event_btnAnularProcesoActionPerformed

        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaGeneralAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaGeneralAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaGeneralAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaGeneralAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaProcesosVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarOrdenesProcesos;
    private javax.swing.JButton btnAnularProceso;
    private javax.swing.JButton btnBuscarOrden;
    private javax.swing.JButton btnCrearProceso;
    private javax.swing.JButton btnFirmarOrden;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificarProceso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlProcesosVenta;
    private javax.swing.JTable tblOrdenes;
    private javax.swing.JTable tblProcesos;
    private javax.swing.JTextField txtAduana;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtComision;
    private javax.swing.JTextField txtEstadoOrden;
    private javax.swing.JTextField txtEstadoProceso;
    private javax.swing.JTextField txtFechaFinProceso;
    private javax.swing.JTextField txtFechaOrden;
    private javax.swing.JTextField txtFechaProceso;
    private javax.swing.JTextField txtIdOrden;
    private javax.swing.JTextField txtIdProceso;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtPagoServicio;
    private javax.swing.JTextField txtPagoTransportista;
    // End of variables declaration//GEN-END:variables
}
