/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.duoc.pty.feriavirtualdesktop.grafica;

import cl.duoc.pty.feriavirtualdesktop.entidades.Orden;
import cl.duoc.pty.feriavirtualdesktop.entidades.RespuestaOrdenListar;
import cl.duoc.pty.feriavirtualdesktop.entidades.RespuestaUsuarioListar;
import cl.duoc.pty.feriavirtualdesktop.entidades.TMOrden;
import cl.duoc.pty.feriavirtualdesktop.entidades.TMUsuario;
import cl.duoc.pty.feriavirtualdesktop.entidades.Usuario;
import cl.duoc.pty.feriavirtualdesktop.negocio.OrdenController;
import cl.duoc.pty.feriavirtualdesktop.negocio.UsuarioController;
import com.sun.javafx.scene.control.skin.VirtualFlow;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author bruunildo
 */
public class VistaReportesAdministrador extends javax.swing.JPanel {
    /**
     * Creates new form ReportesAdministrador
     */
    CardLayout vista;
    public VistaReportesAdministrador() {
        initComponents();
        

 
    }

    
    
        private void inicializarTabla() {
        String cbxopcion = (String)cbxTipoReporteAdministrador.getSelectedItem();   
        
        
        /*
        if (cbxopcion == "23") {
            List<Usuario> usuarios = new ArrayList<>();
            TMUsuario modelo;                         
            modelo = new TMUsuario(usuarios);
            tblReporteAdministrador.setModel(modelo); 
            RespuestaUsuarioListar listaUsuario = new RespuestaUsuarioListar();
            String s = (String)cbxTipoReporteAdministrador.getSelectedItem();
            listaUsuario = UsuarioController.buscarUsuario(s);
            modelo = new TMUsuario(listaUsuario.getUsuarios());
            tblReporteAdministrador.setModel(modelo);
        } else {
                CuadroDialogo.setVisible(true);
        }
        
        */
        
        
        switch (cbxopcion) 
        { 
            case "Usuarios Creados en Plataforma": 
                List<Usuario> usuarios = new ArrayList<>();
                TMUsuario modeloUsuario;                         
                modeloUsuario = new TMUsuario(usuarios);
                RespuestaUsuarioListar listaUsuario = new RespuestaUsuarioListar();
                listaUsuario = UsuarioController.buscarUsuario("");
                modeloUsuario = new TMUsuario(listaUsuario.getUsuarios());
                tblReporteAdministrador.setModel(modeloUsuario);
                TableRowSorter<TableModel> OrdenModeloUsuario = new TableRowSorter<TableModel>(modeloUsuario);
                tblReporteAdministrador.setRowSorter(OrdenModeloUsuario);
                //OrdenModeloUsuario.setRowFilter(RowFilter.regexFilter("23", 0));
            break; 
            case "Procesos de Venta Finalizados": 
            CuadroDialogo.setVisible(true);

            break; 
           case "Total Ordenes Generadas": 
                List<Orden> ordenes = new ArrayList<>();
                TMOrden modeloOrden; 
                modeloOrden = new TMOrden(ordenes);
                RespuestaOrdenListar listaOrden = new RespuestaOrdenListar();
                listaOrden = OrdenController.listarOrden();
                modeloOrden = new TMOrden(listaOrden.getOrdenes());
                tblReporteAdministrador.setModel(modeloOrden);
                
                TableRowSorter<TableModel> OrdenModeloOrden = new TableRowSorter<TableModel>(modeloOrden);
                tblReporteAdministrador.setRowSorter(OrdenModeloOrden);
                
                
            break; 
}
        

        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CuadroDialogo = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReporteAdministrador = new javax.swing.JTable();
        cbxTipoReporteAdministrador = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnReportesAdminsGenerar = new javax.swing.JButton();

        CuadroDialogo.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout CuadroDialogoLayout = new javax.swing.GroupLayout(CuadroDialogo.getContentPane());
        CuadroDialogo.getContentPane().setLayout(CuadroDialogoLayout);
        CuadroDialogoLayout.setHorizontalGroup(
            CuadroDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        CuadroDialogoLayout.setVerticalGroup(
            CuadroDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reportes Administrador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        setPreferredSize(new java.awt.Dimension(200, 200));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblReporteAdministrador.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblReporteAdministrador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblReporteAdministrador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblReporteAdministrador.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblReporteAdministrador.setColumnSelectionAllowed(true);
        tblReporteAdministrador.setEnabled(false);
        tblReporteAdministrador.setGridColor(new java.awt.Color(43, 172, 192));
        tblReporteAdministrador.setRowHeight(25);
        tblReporteAdministrador.getTableHeader().setReorderingAllowed(false);
        tblReporteAdministrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReporteAdministradorMouseClicked(evt);
            }
        });
        tblReporteAdministrador.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tblReporteAdministradorComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tblReporteAdministrador);
        tblReporteAdministrador.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1071, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        cbxTipoReporteAdministrador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbxTipoReporteAdministrador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el Reporte a mostrar..", "Usuarios Creados en Plataforma", "Procesos de Venta Finalizados", "Total Procesos de Venta", "Procesos de Subasta Transp. Finalizados", "Total Procesos Subasta Transp.", "Total Ordenes Generadas" }));
        cbxTipoReporteAdministrador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Generar reporte de:");

        btnReportesAdminsGenerar.setBackground(new java.awt.Color(4, 169, 16));
        btnReportesAdminsGenerar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnReportesAdminsGenerar.setForeground(new java.awt.Color(255, 255, 255));
        btnReportesAdminsGenerar.setText("Generar");
        btnReportesAdminsGenerar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReportesAdminsGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesAdminsGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReportesAdminsGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTipoReporteAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(cbxTipoReporteAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnReportesAdminsGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportesAdminsGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesAdminsGenerarActionPerformed
        inicializarTabla();          
    }//GEN-LAST:event_btnReportesAdminsGenerarActionPerformed

    private void tblReporteAdministradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReporteAdministradorMouseClicked

    }//GEN-LAST:event_tblReporteAdministradorMouseClicked

    private void tblReporteAdministradorComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tblReporteAdministradorComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tblReporteAdministradorComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog CuadroDialogo;
    private javax.swing.JButton btnReportesAdminsGenerar;
    private javax.swing.JComboBox<String> cbxTipoReporteAdministrador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReporteAdministrador;
    // End of variables declaration//GEN-END:variables
}
