/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.duoc.pty.feriavirtualdesktop.grafica;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.SwingUtilities;

/**
 *
 * @author Javier
 */
public class VistaGeneralAdministrador extends javax.swing.JFrame {

    VistaGestionUsuarios vistaGestionUsuarios = new VistaGestionUsuarios();
    VistaProcesosVenta vistaProcesosVenta = new VistaProcesosVenta();
    VistaGestionSubastaTransporte vistaGestionSubastasTransportes = new VistaGestionSubastaTransporte();
    VistaReportesAdministrador vistaReportesAdministrador = new VistaReportesAdministrador();
    CardLayout vista;

    public static String session;

    /**
     * Creates new form VistaGeneralAdministrador
     */
    public VistaGeneralAdministrador() {
        initComponents();
        this.setLocationRelativeTo(null);
        vista = (CardLayout) pnlAdministradorDinamico.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAdministrador = new javax.swing.JLabel();
        lblImageUser = new javax.swing.JLabel();
        pnlbtnAdmin2 = new javax.swing.JPanel();
        lblMenu = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnGestionUsuarios = new javax.swing.JButton();
        btnProcesosVenta = new javax.swing.JButton();
        btnGestionSubastaTransporte = new javax.swing.JButton();
        btnReportesVentas = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnCategoriasProductos = new javax.swing.JButton();
        pnlAdministradorDinamico = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));

        jPanel1.setBackground(new java.awt.Color(43, 172, 192));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 48))); // NOI18N

        lblAdministrador.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        lblAdministrador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdministrador.setText("Administrador");
        lblAdministrador.setToolTipText("");

        lblImageUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImageUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/duoc/pty/feriavirtualdesktop/grafica/imagenes/Grupo 27.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblImageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(592, 592, 592)
                .addComponent(lblAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlbtnAdmin2.setBackground(new java.awt.Color(255, 255, 255));

        lblMenu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(43, 172, 192));
        lblMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenu.setText("Menú");
        lblMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setBackground(new java.awt.Color(43, 172, 192));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        btnGestionUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        btnGestionUsuarios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGestionUsuarios.setText("Gestión de Usuarios");
        btnGestionUsuarios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(43, 172, 192), 1, true));
        btnGestionUsuarios.setBorderPainted(false);
        btnGestionUsuarios.setRequestFocusEnabled(false);
        btnGestionUsuarios.setSelected(true);
        btnGestionUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestionUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestionUsuariosMouseExited(evt);
            }
        });
        btnGestionUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionUsuariosActionPerformed(evt);
            }
        });

        btnProcesosVenta.setBackground(new java.awt.Color(255, 255, 255));
        btnProcesosVenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnProcesosVenta.setText("Procesos de Venta");
        btnProcesosVenta.setBorder(null);
        btnProcesosVenta.setBorderPainted(false);
        btnProcesosVenta.setRequestFocusEnabled(false);
        btnProcesosVenta.setSelected(true);
        btnProcesosVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProcesosVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProcesosVentaMouseExited(evt);
            }
        });
        btnProcesosVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesosVentaActionPerformed(evt);
            }
        });

        btnGestionSubastaTransporte.setBackground(new java.awt.Color(255, 255, 255));
        btnGestionSubastaTransporte.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGestionSubastaTransporte.setText("Gestión de Subasta Transporte");
        btnGestionSubastaTransporte.setBorder(null);
        btnGestionSubastaTransporte.setBorderPainted(false);
        btnGestionSubastaTransporte.setRequestFocusEnabled(false);
        btnGestionSubastaTransporte.setSelected(true);
        btnGestionSubastaTransporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestionSubastaTransporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestionSubastaTransporteMouseExited(evt);
            }
        });
        btnGestionSubastaTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionSubastaTransporteActionPerformed(evt);
            }
        });

        btnReportesVentas.setBackground(new java.awt.Color(255, 255, 255));
        btnReportesVentas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnReportesVentas.setText("Reportes");
        btnReportesVentas.setBorder(null);
        btnReportesVentas.setBorderPainted(false);
        btnReportesVentas.setRequestFocusEnabled(false);
        btnReportesVentas.setSelected(true);
        btnReportesVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportesVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportesVentasMouseExited(evt);
            }
        });
        btnReportesVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesVentasActionPerformed(evt);
            }
        });

        btnCerrarSesion.setBackground(new java.awt.Color(4, 169, 16));
        btnCerrarSesion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        btnCategoriasProductos.setBackground(new java.awt.Color(255, 255, 255));
        btnCategoriasProductos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCategoriasProductos.setText("Categorías Productos");
        btnCategoriasProductos.setBorder(null);
        btnCategoriasProductos.setRequestFocusEnabled(false);
        btnCategoriasProductos.setSelected(true);
        btnCategoriasProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCategoriasProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCategoriasProductosMouseExited(evt);
            }
        });
        btnCategoriasProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriasProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlbtnAdmin2Layout = new javax.swing.GroupLayout(pnlbtnAdmin2);
        pnlbtnAdmin2.setLayout(pnlbtnAdmin2Layout);
        pnlbtnAdmin2Layout.setHorizontalGroup(
            pnlbtnAdmin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGestionUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnProcesosVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGestionSubastaTransporte, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
            .addComponent(btnReportesVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlbtnAdmin2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlbtnAdmin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlbtnAdmin2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(btnCategoriasProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlbtnAdmin2Layout.setVerticalGroup(
            pnlbtnAdmin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlbtnAdmin2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnGestionUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProcesosVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCategoriasProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGestionSubastaTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportesVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pnlAdministradorDinamico.setLayout(new java.awt.CardLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/duoc/pty/feriavirtualdesktop/grafica/imagenes/opacity3.png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        pnlAdministradorDinamico.add(jLabel1, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlbtnAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAdministradorDinamico, javax.swing.GroupLayout.DEFAULT_SIZE, 1592, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlbtnAdmin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAdministradorDinamico, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionUsuariosMouseEntered

        btnGestionUsuarios.setBackground(new Color(253, 187, 72));
    }//GEN-LAST:event_btnGestionUsuariosMouseEntered

    private void btnGestionUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionUsuariosMouseExited
        btnGestionUsuarios.setBackground(Color.white);
    }//GEN-LAST:event_btnGestionUsuariosMouseExited

    private void btnProcesosVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProcesosVentaMouseEntered
        btnProcesosVenta.setBackground(new Color(253, 187, 72));
    }//GEN-LAST:event_btnProcesosVentaMouseEntered

    private void btnProcesosVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProcesosVentaMouseExited
        btnProcesosVenta.setBackground(Color.white);
    }//GEN-LAST:event_btnProcesosVentaMouseExited

    private void btnGestionSubastaTransporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionSubastaTransporteMouseEntered
        btnGestionSubastaTransporte.setBackground(new Color(253, 187, 72));
    }//GEN-LAST:event_btnGestionSubastaTransporteMouseEntered

    private void btnGestionSubastaTransporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionSubastaTransporteMouseExited
        btnGestionSubastaTransporte.setBackground(Color.white);
    }//GEN-LAST:event_btnGestionSubastaTransporteMouseExited

    private void btnGestionUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionUsuariosActionPerformed
        VistaGestionUsuarios vistaGestionUsuarios = new VistaGestionUsuarios();
        pnlAdministradorDinamico.add(vistaGestionUsuarios, "alta");
        vista.show(pnlAdministradorDinamico, "alta");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();


    }//GEN-LAST:event_btnGestionUsuariosActionPerformed

    private void btnGestionSubastaTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionSubastaTransporteActionPerformed
        VistaGestionSubastaTransporte vistaGestionSubastasTransportes = new VistaGestionSubastaTransporte();
        pnlAdministradorDinamico.add(vistaGestionSubastasTransportes, "alta");
        vista.show(pnlAdministradorDinamico, "alta");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_btnGestionSubastaTransporteActionPerformed

    private void btnReportesVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesVentasMouseEntered
        btnReportesVentas.setBackground(new Color(253, 187, 72));
    }//GEN-LAST:event_btnReportesVentasMouseEntered

    private void btnReportesVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesVentasMouseExited
        btnReportesVentas.setBackground(Color.white);
    }//GEN-LAST:event_btnReportesVentasMouseExited

    private void btnReportesVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesVentasActionPerformed
        VistaReportesAdministrador vistaReportesAdministrador = new VistaReportesAdministrador();
        pnlAdministradorDinamico.add(vistaReportesAdministrador, "alta");
        vista.show(pnlAdministradorDinamico, "alta");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_btnReportesVentasActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnProcesosVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesosVentaActionPerformed
        VistaProcesosVenta vistaProcesosVenta = new VistaProcesosVenta();
        pnlAdministradorDinamico.add(vistaProcesosVenta, "alta");
        vista.show(pnlAdministradorDinamico, "alta");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();

    }//GEN-LAST:event_btnProcesosVentaActionPerformed

    private void btnCategoriasProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriasProductosActionPerformed
        // TODO add your handling code here:
        VistaCategoriaProductos vistaCategoriaProductos = new VistaCategoriaProductos();
        pnlAdministradorDinamico.add(vistaCategoriaProductos, "alta");
        vista.show(pnlAdministradorDinamico, "alta");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();

    }//GEN-LAST:event_btnCategoriasProductosActionPerformed

    private void btnCategoriasProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategoriasProductosMouseEntered
        btnCategoriasProductos.setBackground(new Color(253, 187, 72));
    }//GEN-LAST:event_btnCategoriasProductosMouseEntered

    private void btnCategoriasProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategoriasProductosMouseExited
        btnCategoriasProductos.setBackground(Color.white);
    }//GEN-LAST:event_btnCategoriasProductosMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategoriasProductos;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnGestionSubastaTransporte;
    private javax.swing.JButton btnGestionUsuarios;
    private javax.swing.JButton btnProcesosVenta;
    private javax.swing.JButton btnReportesVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAdministrador;
    private javax.swing.JLabel lblImageUser;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JPanel pnlAdministradorDinamico;
    private javax.swing.JPanel pnlbtnAdmin2;
    // End of variables declaration//GEN-END:variables
}
